---
title: "Untitled"
output:
  html_document:
        toc: true
        toc_float: true
        number_sections: true
        theme: 'united'
        highlight: 'tango'
        fig_width: 10
        fig_height: 6
        fig_caption: true
        code_folding: hide
        css: css/styles.css
---

This document was generated on `r Sys.Date()`.

```{r knitropt, echo=F}
knitr::opts_chunk$set(echo=T, message=F, warning=F, error=T, fig.width=10, fig.height=10)
```

```{r packages}
library(dplyr)
library(ggplot2)
library(stringr)
```


Intro {.tabset .tabset-fade .tabset-pills}
=========================================================

## One

```{r}

flipCoin <- function(n, inc){
  flips <- sample(c(inc,-inc), n, TRUE)
  return(data.frame(flip = flips, cum = cumsum(flips)))  
}

limitless <- function(playerA, playerB, inc){
  A <- playerA
  B <- playerB
  
  ponr <- F
  n <- 1
  
  while(!ponr){
    n <- n + 1
    
    if(exists("flips")) flips <- rbind(flips, flipCoin((10^n-nrow(flips)), inc))
    else flips <- flipCoin(10^n, inc)
    
    testA <- which(flips$cum <= A)
    testB <- which(flips$cum >= B)
    
    if((testA %>% length %>% as.logical) & (testB %>% length %>% as.logical)){
      ponr <- T
      if(testA[1] < testB[1]){
        rounds <- testA[1]
        winner <- "playerA"
      } else {
        rounds <- testB[1]
        winner <- "playerB"
      } 
    } else if(testA %>% length %>% as.logical){
      ponr <- T
      winner <- "playerA"
      rounds <- testA[1]
    } else if(testB %>% length %>% as.logical){
      ponr <- T
      winner <- "playerB"
      rounds <- testB[1]
    }
  }
  
  flips <- flips[1:rounds,]
  flips$id <- 1:rounds
  
  out <- list(playerA = A,
              playerB = B,
              winner = winner,
              after_rounds = rounds,
              flips = flips)
  return(out)
}

```

## Two

```{r}
result <- limitless(-100, 100, 1)
plot(x=1:nrow(result$flips), y=result$flips$cum, ty="l", ylab="Total", xlab="rounds")
```

Main {.tabset .tabset-fade .tabset-pills}
=========================================================

```{r}
plotMe <- function(N, X, increment){
  
  #  tmp <- data.frame(no = 1:N)
  #  tmp <- tmp %>% mutate(lim = list(limitless(-X, X, increment)[c("after_rounds", "flips")]))
  tmp <- 1:N
  tmp <- sapply(tmp, function(x){
    out <- limitless(-X, X, increment)
    c(out$after_rounds, out$winner)
  }, simplify = T) %>% t %>% as.data.frame()
  names(tmp) <- c("round", "winner")
  tmp$round <- as.numeric(as.character(tmp$round))
  
  ggplot(tmp, aes(x=round, fill=winner)) + geom_density(alpha=0.5)
  return(tmp)
}
```


## X = 10, N = 1000

```{r}
X <- 10
increment <- 1
N <- 1000

tmp <- plotMe(N, X, increment)

ggplot(tmp, aes(x=round, fill=winner)) + geom_density(alpha=0.5) + labs(x="rounds played") +
  geom_vline(xintercept = mean(tmp$round), linetype=1, color="red") +
  geom_vline(xintercept = median(tmp$round), linetype=2, color="red") +
  geom_vline(xintercept = X*X, linetype=1, color="blue") 
# ggplot(tmp, aes(x=round/X, fill=winner)) +
#   geom_density(alpha=0.5) +
#   geom_vline(xintercept = median(tmp$round)/X, color="red")

summary(tmp)
```


## X = 10, N = 10000

```{r}
X <- 10
increment <- 1
N <- 10000

tmp <- plotMe(N, X, increment)

ggplot(tmp, aes(x=round, fill=winner)) + geom_density(alpha=0.5)+ labs(x="rounds played") +
    geom_vline(xintercept = mean(tmp$round), linetype=1, color="red") +
  geom_vline(xintercept = median(tmp$round), linetype=2, color="red") +
  geom_vline(xintercept = X*X, linetype=1, color="blue") 

summary(tmp)
```

## X = 10, N = 50000

```{r}
X <- 10
increment <- 1
N <- 50000

tmp <- plotMe(N, X, increment)

ggplot(tmp, aes(x=round, fill=winner)) + geom_density(alpha=0.5)+ labs(x="rounds played") +
    geom_vline(xintercept = mean(tmp$round), linetype=1, color="red") +
  geom_vline(xintercept = median(tmp$round), linetype=2, color="red") +
  geom_vline(xintercept = X*X, linetype=1, color="blue") 

summary(tmp)
```


## X = 20, N = 1000

```{r}
X <- 20
increment <- 1
N <- 1000

tmp <- plotMe(N, X, increment)

#tmp %>% density() %>% plot(., main="Rounds till end of game")

ggplot(tmp, aes(x=round, fill=winner)) + geom_density(alpha=0.5)+ labs(x="rounds played")+
    geom_vline(xintercept = mean(tmp$round), linetype=1, color="red") +
  geom_vline(xintercept = median(tmp$round), linetype=2, color="red") +
  geom_vline(xintercept = X*X, linetype=1, color="blue") 

summary(tmp)

```


## X = 20, N = 10000

```{r}
X <- 20
increment <- 1
N <- 10000

tmp <- plotMe(N, X, increment)

ggplot(tmp, aes(x=round, fill=winner)) + geom_density(alpha=0.5)+ labs(x="rounds played") +
    geom_vline(xintercept = mean(tmp$round), linetype=1, color="red") +
  geom_vline(xintercept = median(tmp$round), linetype=2, color="red") +
  geom_vline(xintercept = X*X, linetype=1, color="blue") 

summary(tmp)
```


```{r, eval=F}
X <- 10
increment <- 1

tmp <- 1:100
tmp <- lapply(tmp, function(y){
  tmp  <- limitless(-X, X, increment)
  out <- cbind(tmp$flips, no=y, rounds=tmp$after_rounds)
  return(out)
  }) 

tmp <- do.call(rbind, tmp)

pl1 <- ggplot(tmp, aes(x=id, y=cum, group=as.factor(no))) + geom_line(alpha=0.2) 
ggplot()  +  geom_line(data=tmp %>% group_by(id) %>% summarise(mean = mean(cum)), aes(x=id, y=mean), color="red")

ggplot() + 
  geom_line(data=tmp, aes(x=id, y=cum, group=as.factor(no)), alpha=0.2) +
  geom_line(data=tmp %>% group_by(id) %>% summarise(mean = mean(cum)), aes(x=id, y=mean), color="red")
```


